### ISSUE TITLE
API Retrieve User Details

### ISSUE THREAD

**Issue by JonPeeAir** [HTSagara/PRJ-566-ZAA-Team-1#107]
`GET /user`
This api will be used for populating the "Profile Page" with the user's details.

Notes:
- This task needs #106 to be completed first before starting.
- Check out the [Boto3 Docs](https://boto3.amazonaws.com/v1/documentation/api/latest/index.html#) for retrieving user
- You may need the user's access token for this

**Comment by HTSagara** [comment]
I was able to retrieve the user's details using jwt!

[Image](https://github.com/user-attachments/assets/b03716ba-cf63-4652-9ceb-4929b801a250)

I will try to do it using boto3

**Comment by JonPeeAir** [comment]
> I was able to retrieve the user's details using jwt!
> 
> [Image](https://github.com/user-attachments/assets/b03716ba-cf63-4652-9ceb-4929b801a250)
> 
> I will try to do it using boto3

Was it by using id token?

Cus ye lets try to access token asuch as possible because i read somewhere how thats more secure and i think using boto3 u can get user info using access token

Lets try to use access token for everything as much as possible for consistency.

**Comment by HTSagara** [comment]
I used the access token, but didn't use boto3

**Comment by JonPeeAir** [comment]
> I used the access token, but didn't use boto3

Ohhh, maybe we can use that approach as well if its cleaner than using boto3
