### ISSUE TITLE
1 - Functional Requirements

### ISSUE THREAD

**Issue by JonPeeAir** [HTSagara/PRJ-566-ZAA-Team-1#11]
# Functional Requirements (what the system must do)

## Upload and save books

- Each user has their own category of books

## Read books

  - save/display reading progress

  - highlight text
  
  - change reading view
      - fonts
      - line width
      - line height

## AI integration
  - create an image based on highlighted text using AI

## Users

- User Creation (sign up)
    - first name
    - last name
    - email
    - age

- Login/Logout system
    - login with email and password (AWS)
    - forget password (AWS)

- Track user activity
    - logins
    - logouts

**Comment by HTSagara** [comment]
Postponed for next week
