### ISSUE TITLE
API Upload Book

### ISSUE THREAD

**Issue by JonPeeAir** [HTSagara/PRJ-566-ZAA-Team-1#118]
The implementation for this will be pretty similar to Fragments in CCP

this task needs:
- #116 
- #117
___

Before implementing endpoint, we need to create `Book` class
- `Book` must have the following attributes: 
  - `id: string` - random UUID for book
  - `ownerId: string` - hashed email of user
  - `created: date` - date created
  - `updated: date` - date updated
  - `type: string` - "epub" or "pdf"
  - `size: int` - size of the file
  - `title: string` - book's title
  - `author: string` - book's author
  - `imgUrl: string [default: null]` - book's cover image (aws url)
- `Book` must have the following methods:
  - `setBookContent(bookFile)` 
    - uploads the book file to S3
    - book file will be stored in `<email hash>/<book UUID>`
  - `save()` 
    - upload book image, if any, to s3
      - images will be stored in `<email hash>/images/<book UUID>.jpg|png|whatever`
      - then get the public url for image
    - update `imgUrl` to point to the public url for the recently uploaded image
    - upload the book metadata to MongoDb
    - collection name should be ownerId (hash of user email)
    - object id should be the book id (Random UUID for book)
___

Implementing `POST /book`
- receives `multipart/form-data`
  - `file` form field: the book file
  - `metadata` form field: the book metadata
    - Book Title
      - if not provided, try to extract from file
      - if unable to extract from file, set title to filename
    - Book Author
      - if not provided, try to extract from file
      - if unable to extract from file, set author to "N/A"
    - Book image
      - if not provided, try to extract from file
      - if unable to extract from file, leave as null (frontend will show generic image)
- create `Book` object using file info and metadata
- upload book file to s3 by running `Book.setBookContent(file)`
- upload book metadata to mongodb by running `book.save()`
- return book metadata as json
  - `id: string` - random UUID for book
  - `ownerId: string` - hashed email of user
  - `created: date` - date created
  - `updated: date` - date updated
  - `type: string` - "epub" or "pdf"
  - `size: int` - size of the file
  - `title: string` - book's title
  - `author: string` - book's author
  - `imgUrl: string [default: null]` - book's cover image
___
Sample code on how to receive `multipart/form-data` from chatgpt

```python
from fastapi import FastAPI, UploadFile, File
from fastapi.responses import JSONResponse
from pydantic import BaseModel
import os

app = FastAPI()

# Define the folder to store uploaded files
UPLOAD_FOLDER = './uploads'
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

# Allowed file types
ALLOWED_EXTENSIONS = {'pdf', 'epub'}

class Metadata(BaseModel):
    title: str
    author: str
    description: str

@app.post("/upload")
async def upload_file(file: UploadFile = File(...), metadata: Metadata):
    # Check if the uploaded file has an allowed extension
    if not file.filename.endswith(tuple(ALLOWED_EXTENSIONS)):
        return JSONResponse(content={'error': 'File type not allowed. Only PDF or EPUB is allowed.'}, status_code=400)

    # Save the file
    file_path = os.path.join(UPLOAD_FOLDER, file.filename)
    with open(file_path, "wb") as f:
        content = await file.read()
        f.write(content)

    # Return response with file path and metadata
    return {
        'message': 'File successfully uploaded',
        'file_path': file_path,
        'metadata': metadata.dict()  # Convert Pydantic model to dict
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8000)
```

How to call api using curl

```curl
curl -X POST "http://127.0.0.1:8000/upload" \
     -F "file=@path_to_your_file.epub" \
     -F 'metadata={"title": "Your Book Title", "author": "Author Name", "description": "A brief description of the book."}'
```

**Comment by HTSagara** [comment]
**Updates**
We are able to save the file in the S3 and the metadata in the MongoDB.

However it throws an 500 error that we need to dig a little deeper.
![Image](https://github.com/user-attachments/assets/2ff75baf-001a-4812-906c-e8a1dce908e4)

Also, it is not saving the last modified and the size. It might be some problem with the Book class that I will investigate.![Image](https://github.com/user-attachments/assets/646814e3-e7db-4b98-a924-26fcb513536b)

Regarding the metadata. It seems solid.
![Image](https://github.com/user-attachments/assets/ada87a82-2580-43d5-8499-f6f51d6c27ca)
