### ISSUE TITLE
2 - Nonfunctional Requirements

### ISSUE THREAD

**Issue by JonPeeAir** [HTSagara/PRJ-566-ZAA-Team-1#12]
# Non-functional Requirements (what the system must have)

## Operational Requirements

- API
    - Backend must operate in linux environment (EC2)
    - Python (fastapi)

- Application must run across multiple platforms
    - Web
    - Andoid
    - IOS

- AI
    - model: https://huggingface.co/runwayml/stable-diffusion-v1-5

## Performance Requirements

- AI model should take no more than 2 minutes to generate an image
- Books should load in 2-3 minutes

## Security Requirements

- only hashed/encrypted passwords must be stored in the database
- only users aged 18+ are allowed to set explicit content on or off

## Cultural Requirements

- nothing

**Comment by HTSagara** [comment]
Postponed for next week
