### ISSUE TITLE
Develop Navbar

### ISSUE THREAD

**Issue by JonPeeAir** [HTSagara/PRJ-566-ZAA-Team-1#159]
Should have wordvision title
user profile icon on top right
clicking user profile shows dropdown
- View profile: routes to user profile page
- logout: logs out, routes to landing page

Try to make it a template as much as possible so multiple pages/components can use it.

Change library to home (keep the book icon)
Move profile to drawer
just keep the tabs
for now we only have the one tab (home)

**Comment by HTSagara** [comment]
add the profile in the drawer and change the library to home
