### ISSUE TITLE
Problem Statement

### ISSUE THREAD

**Issue by JonPeeAir** [HTSagara/PRJ-566-ZAA-Team-1#8]

**Comment by samrath2003** [comment]
The Problem of: 

The Problem of having visual representation of the content people consume through books. 

Affects: 

The users who want to seek more immersive experience, People with Aphantasia 

The impact of which is: 

People facing difficulty in fully understanding the text and beginners getting discouraged to be regular readers. 

A successful solution would: 

A successful solution would help Visual learners, individuals with certain cognitive differences, and those seeking a more immersive experience take a deep dive into the text they are reading. It may include stories, fantasy, documentary , satirical texts, etc.
